### ISSUE TITLE
Unable to create database using IP

### ISSUE THREAD

**Issue by aburhan** [momander/cymbal-eats#1]
When I run this command

gcloud sql users create $DB_USER \
--instance=$DB_HOST \ <--earlier step step DB_HOST to the private IP of the instance. 
--password=$DB_PASSWORD

I changed DB_HOST to "menu_catalog" and this step works fine.

**Comment by gitrey** [comment]
@aburhan I've opened PR to switch to INSTANCE NAME - https://github.com/momander/cymbal-eats/pull/8

**Comment by gitrey** [comment]
Fixed in https://github.com/momander/cymbal-eats/pull/8
